package_name: dataset


#data
raw_data_file: data/raw_data/
datainterimdirectory: data/interim/
dataprocesseddirectory: data/processed/
datalink: https://raw.githubusercontent.com/nickkats1/sklearn_only/refs/heads/main/houseprice/data/raw_data/dataset.csv
datainterim: data/interim/

#train/test paths
training_data_file: train.csv
test_data_file: test.csv

#images from training
images_dir: images/

dataprocessed: data/processed
model_path: models/model.joblib
resultsrawpath: results/results_raw.joblib
resultsevaluatedpath: results/results_evaluated.joblib




