columns:
  year: int64
  age: int64
  beds: int64
  baths: float64
  home_size: int64
  parcel_size: int64
  pool: int64
  dist_cbd: float64
  dist_lakes: float64
  x_coord: float64
  y_coord: int64


target: price