#data
datalink: https://raw.githubusercontent.com/nickkats1/sklearn_only/refs/heads/main/customers/data/raw/customer.csv
dataname: customer
dataraw_dir: data/raw/
interim_dir: data/interim/
data_preprocessed: data/processed/






#model
model_path: models/model.joblib




resultsrawpath: results/results_raw.joblib
resultsevaluatedpath: results/results_evaluated.joblib


#images
imagesdir: images/

#params
model_name: RandomForestRegressor
max_depth: 10
min_samples_leaf: 1
min_samples_split: 2
n_estimators: 100