#data


#raw_data
data_raw: data/raw/customers.csv
train_raw: data/raw/train.csv
test_raw: data/raw/test.csv
url_link: https://raw.githubusercontent.com/nickkats1/sklearn_only/refs/heads/main/customers/data/raw/customers.csv

#processed data
processed_path: data/processed/
processed_train: data/processed/trian.csv
processed_test: data/processed/test.csv


#model paths




# model paths
trained_model_path: models/model.joblib
preprocessed_path: models/scaler.joblib

features:
 - app_id
 - ssn
 - zip_code
 - income
 - homeownership
 - purchases
 - credit_limit
 - fico
 - num_late
 - past_def
 - num_bankruptcy
 - avg_income
 - density
 


target: log_odds_utils


#params
test_size: 0.2
random_state: 42









