# raw paths
raw_path: data/raw/data.csv
train_raw: data/raw/train.csv
test_raw: data/raw/test.csv
train_target_raw: data/raw/y_train.csv
test_target_raw: data/raw/y_test.csv

#processed paths
processed_path: data/processed/
train_processed: data/processed/train.csv
test_processed: data/processed/test.csv

# model paths

model_path: models/best_model.pkl





features:
 - ssn
 - zip_code
 - income
 - homeownership
 - purchases
 - credit_limit
 - fico
 - num_late
 - past_def
 - num_bankruptcy
 - avg_income
 - avg_income
 - density
 

#target variable

target: log_odds_utils










